//
//  UIColor+Metar.swift
//
//  Generated by Zeplin on 2/8/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved.
//

import UIKit

extension UIColor {

    class func mtrGreyColor() -> UIColor {
        return UIColor(red: 91.0 / 255.0, green: 103.0 / 255.0, blue: 112.0 / 255.0, alpha: 1.0)
    }

    class func mtrDarkBlueColor() -> UIColor {
        return UIColor(red: 21.0 / 255.0, green: 38.0 / 255.0, blue: 51.0 / 255.0, alpha: 1.0)
    }

    class func mtrBlueColor() -> UIColor {
        return UIColor(red: 83.0 / 255.0, green: 217.0 / 255.0, blue: 250.0 / 255.0, alpha: 1.0)
    }
    
}
