app_identifier 'be.fousa.metar'
username 'fousa'

default_language 'en'

hide_transporter_output

app '991619333'

title({
  'en-US' => 'METAR - Aviation Weather for Pilots'
})

# Set the changelog.
# changelog({
 # 'en-US' => ''
# })

# The application description.
description({
    'en-US' => File.read('descriptions/en.txt')
})

# The application keywords.
keywords({
  'en-US' => ['metar', 'icao']
})
# The current application version.
version '1.0.0'

# The support URL.
support_url 'http://fousa.be'

# The marketing URL.
marketing_url 'http://fousa.be'

# The app review information.
app_review_information({
  first_name: 'Jelle',
  last_name: 'Vandebeeck'
})

# Copyright information.
copyright "#{Time.now.year} Jelle Vandebeeck"
