fastlane_version "1.33.6"

lane :beta do
  # Update build number, tag and commit.
  increment_build_number
  commit_version_bump
  add_git_tag prefix: 'v'
  push_to_git_remote local_branch: 'master'

  # Setup signing.
  sigh app_identifier: 'be.fousa.metar'

  # Build the application.
  gym(scheme: "Metar")

  # Deploy the application to TestFlight.
  deliver(beta: true)
end
