fastlane_version '1.50.0'

lane :deploy do
  # Run tests in given simulator
  xctest(
    workspace:   'Metar.xcworkspace',
    scheme:      'Metar',
    clean:       true,
    destination: 'platform=iOS Simulator,name=iPhone 6',
    reports: [
      { report: 'html' }
    ]
  )

  # Update build number, tag and commit.
  increment_build_number

  # Fetch certificates.
  match(type: 'appstore')

  # Build the application.
  gym(
    scheme: 'Metar',
    clean:  true
  )

  # Deploy the application to TestFlight.
  pilot

  # Tag and push the version bump.
  commit_version_bump
  add_git_tag prefix: 'v'
  push_to_git_remote

  # Cleanup the workspace.
  clean_build_artifacts
end
