fastlane_version '1.56.0'

lane :deploy do
  # Run the tests.
  # run_tests

  # Fetch the translations.
  update_translations

  # Build the application and bump the version number.
  last_hash = build

  # Deploy the application to TestFlight.
  upload(changelog_begin_tag: last_hash)

  # Cleanup.
  cleanup
end

####################
### PRIVATE LANE ###
####################

# Fetch the latest tagged commit hash.
private_lane :last_git_tag_hash do
  sh("git rev-parse --verify #{last_git_tag}").strip
end

# Run the tests.
private_lane :run_tests do
  # Run tests
  scan(scheme: "Metar")
end

# Build and upload the application.
private_lane :build do
  # Update build number, tag and commit.
  increment_build_number

  # Fetch certificates.
  match(type: 'appstore')

  # Build the application.
  gym(
    scheme: 'Metar',
    clean:  true
  )

  # Tag and push the version bump.
  commit_version_bump
  add_git_tag prefix: 'v'
  push_to_git_remote

  last_git_tag_hash
end

# Upload the application to TestFlight.
private_lane :upload do |options|
  # Fetch the changelog.
  changelog = changelog_from_git_commits(
    between: [options[:changelog_begin_tag],'HEAD'],
    pretty: '- %s'
  )

  # Upload to Fabric
  crashlytics(
    api_token:    ENV['FABRIC_API_KEY'],
    build_secret: ENV['FABRIC_BUILD_SECRET'],
    ipa_path:     'Metar.ipa',
  )

  # Deploy the application to TestFlight.
  pilot(
#     distribute_external: true,
    changelog: changelog
  )
end

# Cleanup the workspace.
private_lane :cleanup do
  clean_build_artifacts
end
