# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
  "iPad Air"
])

languages([
  'en-US',
  'de-DE',
  'it-IT'
])

# Where should the resulting screenshots be stored?
screenshots_path "./screenshots"

clear_previous_screenshots
